asset/urls.py
from django.urls import path
from .views import (create_asset_cat,list_asset_cat,list_asset_manage,retrive_update_asset_manage,generate_csv,add_image_asset,
                   pie_chart,retrive_update_asset_type,delete_asst_type,create_asset_manage,delete_asst_mang_new,bar_chart_view)
app_name ="asset"

urlpatterns = [
    path('asset-catg/',create_asset_cat, name='asst_catg'),
    path('list-asset-cat/',list_asset_cat,name='lst_ast_catg'),
    path('assest-type-details/<int:pk>/', retrive_update_asset_type, name='record_details'),
    path('delete/<int:pk>/', delete_asst_type, name='delete_asst_cat'),
    path('asset-manage/',create_asset_manage, name='asst_manage'),
    path('list-asset-manage/',list_asset_manage,name='lst_ast_manage'),
    path('assest-manage-details/<int:pk>/', retrive_update_asset_manage, name='record_manage_details'),
    path('generate-csv/', generate_csv, name='generate_csv'),
    path('pie-chart/', pie_chart, name='pie_chart'),
    path('bar-chart/', bar_chart_view, name='bar-chart'),
    path('delete-new/<int:pk>/', delete_asst_mang_new, name='delete_asst_mang_new'),
    path('asset-images/',add_image_asset,name='add_images')

]

assettracker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authentication.urls')),
    path('home/',include('dashboard.urls')),
    path('asst/',include('asset.urls')),
]
# if settings.DEBUG:  
#         urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

dashboard/urls.py
from django.urls import path
from .views import home_page,home_page_pi

app_name = 'dashboard'
urlpatterns = [
    path('', home_page, name='home'),## Now Not used
    path('chart/', home_page_pi, name='home_pi'),
]

asset/models.py
from django.db import models
import uuid

# Create your models here.


class AssetCatg(models.Model):

    asset_cat = models.CharField(max_length=120,unique=True)
    asset_discription = models.TextField(max_length=500,blank=False,null=True)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now= True)


    class Meta:
        ordering = ('-created_on',)

    def __str__(self):
        return self.asset_cat
    
class AssetManage(models.Model):

    asset_name = models.CharField(max_length=120)
    asset_code = models.CharField(max_length=16,unique=True)
    asset_catg = models.ForeignKey(AssetCatg,on_delete= models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now= True)
    is_active = models.BooleanField(default=False)
    # image_url = models.ImageField(upload_to = 'images/', blank=True, null=True)

    class Meta:
        ordering = ('-created_on',)

    def save(self, *args, **kwargs):
        if not self.asset_code:
            self.asset_code = uuid.uuid4().hex[:16]  # Generates a 16-digit UUID
        super().save(*args, **kwargs)

    def __str__(self):
        return self.asset_name


class Image(models.Model):
    main_model = models.ForeignKey(AssetManage, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')

templates/assest/asset_manage_create.html
{% extends 'dashboard/home.html' %}

{% block home_main_content %} 

    <div class="card card-info">
        <div class="card-header">
            <h3 class="card-title">Asset Managemet</h3>
        </div>
        <div class="card-body">
            <h2 class="my-5">{% if update %}Details & Update Assets{% else %}Create a Assets{% endif %}</h2>
            <form method="POST" enctype="multipart/form-data" class="assest-cat-type">
                {% csrf_token %}
                {% if images %}
                    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                            <div class="carousel-inner">
                                {% for image in images %}
                                    <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                        <img class="d-block w-100" src="{{ image.image.url }}" alt="Slide {{ forloop.counter }}" style="max-width: 100%; max-height: 400px;">
                                    </div>
                                {% endfor %}
                            </div>
                        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                        </a>
                    </div>
                {% endif %}

                <div class="form-group">
                    <label>Assest Name</label>
                    <input type="text" class="form-control my-colorpicker1 colorpicker-element {% if form.asset_name.errors %}is-invalid{% endif %}"
                         data-colorpicker-id="1" name="asset_name" value='{{ form.asset_name.value|default:"" }}' id="id_asset_name">
                </div>


                <div class="col-md-6">
                    <div class="form-group">
                      <label>Asset Type</label>
                      <select class="form-control select2 select2-hidden-accessible" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true" name="asset_catg" id="id_asset_catg" >
                        {% for assest in asset_type %}
                            <option value="{{ assest.id }}" {% if assest.id == form.asset_catg.value %}selected{% endif %}>{{ assest.asset_cat }}</option>
                        {% endfor %}
                        </select>
                    </div>
                </div>

                <div class="checkbox">
                    <label><input type="checkbox" name="is_active" id="id_is_active" {% if form.is_active.value %} checked {% endif %} >Is Active</label>
                </div>

                <button class="btn btn-primary ml-2" type="submit">{% if update %}Update{% else %}Save{% endif %}</button>
                {% if update %}<button type="button" id='delete-btn' class="btn btn-danger"><a style="color: white;" href="{% url 'asset:delete_asst_mang_new' obj_id.id %}">Delete</a></button>
                {% endif %}
                <button type="button" class="btn btn-secondary"><a style="color: white;" href="{% url "asset:lst_ast_manage" %}">Cancel</a></button>
             </form>
        </div>
    </div> 
{% endblock  %}

{% block js_block %} 
    <script>
        document.getElementById('delete-btn').addEventListener('click', function(event) {
            // Prevent the default behavior of the link
            event.preventDefault();
            
            // Display an alert message
            var confirmation = confirm('Are you sure you want to delete this object?');
            
            // If user confirms deletion, proceed with the link action
            if (confirmation) {
                window.location.href = this.querySelector('a').href;
            }
        });
    </script>
{% endblock %}

templates/assest/asset_type_create.html
{% extends 'dashboard/home.html' %}

{% block home_main_content %} 

    <div class="card card-info">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert">
                        {{ message.tags }} : {{ message }}
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="card-header">
            <h3 class="card-title">Asset Type</h3>
        </div>
        <div class="card-body">
            <h2 class="my-5">{% if update %}Details and Update{% else %}Create a Type{% endif %}</h2>
            <form method="POST" enctype="multipart/form-data" class="assest-cat-type">
                {% csrf_token %}
                <div class="form-group">
                    <label>Asset Type Name</label>
                    <input type="text" class="form-control my-colorpicker1 colorpicker-element {% if form.email.errors %}is-invalid{% endif %}"
                         data-colorpicker-id="1" name="asset_cat" value='{{ form.asset_cat.value|default:"" }}' id="id_asset_cat">
                </div>
            

                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                        <label>Discription</label>
                            <textarea class="form-control" rows="3"  id="id_asset_discription" cols="40" rows="10"
                                name="asset_discription" value='{{ form.asset_discription.value|default:"" }}'>{% if update %}{{ form.asset_discription.value }}{% endif%}</textarea>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary ml-2" type="submit">{% if update %}Update{% else %}Save{% endif %}</button>
                {% if update %}<button type="button" id='delete-btn-type' class="btn btn-danger"><a style="color: white;" href="{% url 'asset:delete_asst_cat' obj_id %}">Delete</a></button>
                <button type="button" class="btn btn-secondary"><a style="color: white;" href="{% url "asset:lst_ast_catg" %}">Cancel</a></button>
                {% else %}
                <button type="button" class="btn btn-secondary"><a style="color: white;" href="{% url "dashboard:home_pi" %}">Cancel</a></button>
                {% endif %}
            </form>
        </div>
    </div> 
{% endblock  %}

{% block js_block %} 
    <script>
        document.getElementById('delete-btn-type').addEventListener('click', function(event) {
            // Prevent the default behavior of the link
            event.preventDefault();
            
            // Display an alert message
            var confirmation = confirm("Are you sure? If you delete this asset type, all assets under this asset type will be deleted too!");
            
            // If user confirms deletion, proceed with the link action
            if (confirmation) {
                window.location.href = this.querySelector('a').href;
            }
        });
    </script>
{% endblock %}

templates/assest/image_add.html
{% extends 'dashboard/home.html' %}

{% block home_main_content %} 

{% comment %} <form method="post" enctype="multipart/form-data">  
    {% csrf_token %}  
    {{ form.as_p }}  
    <button type="submit">Upload</button>  
</form>   {% endcomment %}
<div class="card card-info">
    <div class="card-header">
        <h3 class="card-title">ASSET IMAGE</h3>
    </div>
    <div class="card-body">
        <h2 class="my-5">Upload Image</h2>
        <form method="POST" enctype="multipart/form-data" class="assest-cat-type">
            {% csrf_token %}
            {% comment %} <div class="form-group">
                <label>Asset Image</label>
                <input type="file" class="form-control my-colorpicker1 colorpicker-element {% if form.asset_name.errors %}is-invalid{% endif %}"
                     data-colorpicker-id="1" name="asset_name" value='{{ form.asset_name.value|default:"" }}' id="id_asset_name">
            </div> {% endcomment %}

            <div class="mb-6">
                <label for="id_image" class="form-label">Image</label>
                <input class="form-control" type="file" id="id_image" name="image" multiple>
            </div>


            <div class="col-md-6">
                <div class="form-group">
                  <label>Select Asset</label>
                  <select class="form-control select2 select2-hidden-accessible" id="user_select_img" style="width: 100%;" data-select2-id="1" tabindex="-1" aria-hidden="true" name="main_model" id="id_asset_catg" >
                    {% for record in asset %}
                        <option value="{{ record.id }}" >{{record.asset_name}}</option>
                    {% endfor %}
                    </select>
                </div>
            </div>
            <button class="btn btn-primary ml-2" type="submit">Upload</button>
            <button type="button" name="cancel" class="btn btn-secondary"><a style="color: white;" href="{% url "asset:lst_ast_manage" %}" id="img_anchor_id">Cancel</a></button>

         </form>
    </div>
</div> 

{% endblock  %}

{%  block js_block %}


{% endblock %}

templates/assest/list_asset_cat_view.html
{% extends 'dashboard/home.html' %}



{% block home_main_content %} 

<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">DataTable with minimal features &amp; hover style</h3>
        </div>
        <div class="card-body">
          <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <div class="row">
              <div class="col-sm-12 col-md-6"></div>
              <div class="col-sm-12 col-md-6"></div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" aria-describedby="example2_info">
                  <thead>
                    <tr>
                      <th class="sorting sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Assest Name</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Discription</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Created Date</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Updated Date</th>
                    </tr>
                  </thead>
                  {% for obj in page_obj %}
                    <tbody>
                     
                        <tr class="odd">
                        <td class="dtr-control sorting_1" tabindex="0"> <a href="{% url 'asset:record_details' obj.id %}">{{ obj.asset_cat }}                      </a> 
                        </td>
                        <td>{{ obj.asset_discription|truncatechars:50 }}</td>
                        <td>{{ obj.created_on }}</td>
                        <td>{{ obj.updated_on }}</td>
                        </tr>
                    </tbody>
                  {% endfor %}
                  <tfoot>
                    <tr>
                      <th rowspan="1" colspan="1">Assest Name</th>
                      <th rowspan="1" colspan="1">Discription</th>
                      <th rowspan="1" colspan="1">Created Date</th>
                      <th rowspan="1" colspan="1">Updated Date</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
            <!-- pagination -->
            {% comment %} <div class="row">
                <nav class="col-lg-6 offset-lg-3 mt-4 d-flex justify-content-center">
                  <ul class="pagination">
            
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                      <a class="page-link" href="#">Previous</a>
                    </li>
                    {% endif %}
              
                    {% for i in page_obj.paginator.page_range %}
                    <li class=" page-item {% if page_obj.number == i %}active{% endif %}">
                        <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                    </li>
                    {% endfor %}
            
                    {% if page_obj.has_next %}
                    <li class="page-item">
                      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                      <a class="page-link" href="#">Next</a>
                    </li>
                    {% endif %}
                  </ul>
                </nav>
              </div> {% endcomment %}

              <div class="row">
                <div class="col-sm-12 col-md-7">
                  <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                    <ul class="pagination">
                      {% if page_obj.has_previous %}
                      <li class="paginate_button page-item previous" id="example1_previous">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                      </li>
                      {% else %}
                      <li class="paginate_button page-item previous disabled" id="example1_previous">
                        <a class="page-link" href="#">Previous</a>
                      </li>
                      {% endif %}
                      {% for i in page_obj.paginator.page_range %}
                      <li class=" paginate_button page-item {% if page_obj.number == i %}active{% endif %}">
                          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                      </li>
                      {% endfor %}
                      {% if page_obj.has_next %}
                        <li class="paginate_button page-item next" id="example1_next">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                      {% else %}
                        <li cclass="paginate_button page-item next disabled" id="example1_next">
                            <a class="page-link" href="#">Next</a>
                        </li>
                      {% endif %}          
            
                    </ul>
                  </div>
                </div>
              </div>



            <!-- end of pagination-->
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

templates/assest/list_asset_manage.html
{% extends 'dashboard/home.html' %}

{% block home_main_content %} 

<div class="row">
    <div class="col-12">
      <div class="card">
        {% comment %} <div class="card-header">
            <h3 class="card-title">DataTable</h3>
        </div>         {% endcomment %}

        <div class="card-header d-flex justify-content-between align-items-center">
            <div>
                <h3 class="card-title m-0">DataTable</h3>
            </div>
            <div style="position: absolute; top: 0; right: 0;">
                {% comment %} <button class="btn btn-primary">Download</button> {% endcomment %}
                <button type="button" class="btn btn-primary"><a style="color: white;" href="{% url 'asset:generate_csv'%}">Download</a></button>
            </div>
        </div>
        
        <div class="card-body">
          <div id="example2_wrapper" class="dataTables_wrapper dt-bootstrap4">
            <div class="row">
              <div class="col-sm-12 col-md-6"></div>
              <div class="col-sm-12 col-md-6"></div>
            </div>
            <div class="row">
              <div class="col-sm-12">
                <table id="example2" class="table table-bordered table-hover dataTable dtr-inline" aria-describedby="example2_info">
                  <thead>
                    <tr>
                      <th class="sorting sorting_asc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-sort="ascending" aria-label="Rendering engine: activate to sort column descending">Name</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Type</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">UUID Code</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Is Active</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Created Date</th>
                      <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending">Updated Date</th>
                    </tr>
                  </thead>
                  {% for obj in page_obj %}
                    <tbody>
                     
                        <tr class="odd">
                        <td class="dtr-control sorting_1" tabindex="0"> <a href="{% url 'asset:record_manage_details' obj.id %}">{{ obj.asset_name }}</a> 
                        </td>
                        <td>{{ obj.asset_catg }}</td>
                        <td>{{ obj.asset_code }}</td>
                        <td>{{ obj.is_active }}</td>
                        <td>{{ obj.created_on }}</td>
                        <td>{{ obj.updated_on }}</td>
                        </tr>
                    </tbody>
                  {% endfor %}
                  <tfoot>
                    <tr>
                      <th rowspan="1" colspan="1">Name</th>
                      <th rowspan="1" colspan="1">Type</th>
                      <th rowspan="1" colspan="1">UUID Code</th>
                      <th rowspan="1" colspan="1">Is Active</th>
                      <th rowspan="1" colspan="1">Created Date</th>
                      <th rowspan="1" colspan="1">Updated Date</th>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
            <!-- pagination -->
              <div class="row">
                <div class="col-sm-12 col-md-7">
                  <div class="dataTables_paginate paging_simple_numbers" id="example1_paginate">
                    <ul class="pagination">
                      {% if page_obj.has_previous %}
                      <li class="paginate_button page-item previous" id="example1_previous">
                        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
                      </li>
                      {% else %}
                      <li class="paginate_button page-item previous disabled" id="example1_previous">
                        <a class="page-link" href="#">Previous</a>
                      </li>
                      {% endif %}
                      {% for i in page_obj.paginator.page_range %}
                      <li class=" paginate_button page-item {% if page_obj.number == i %}active{% endif %}">
                          <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                      </li>
                      {% endfor %}
                      {% if page_obj.has_next %}
                        <li class="paginate_button page-item next" id="example1_next">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                        </li>
                      {% else %}
                        <li cclass="paginate_button page-item next disabled" id="example1_next">
                            <a class="page-link" href="#">Next</a>
                        </li>
                      {% endif %}          
                    </ul>
                  </div>
                </div>
              </div>
            <!-- end of pagination-->
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

templates/assest/tag_create.html
{% extends 'dashboard/home.html' %}

{% block home_main_content %} 

    <div class="card card-info">
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <div class="alert alert-warning" role="alert">
                        {{ message.tags }} : {{ message }}
                    </div>
                {% endfor %}
            </ul>
        {% endif %}
        <div class="card-header">
            <h3 class="card-title">Asset Type</h3>
        </div>
        <div class="card-body">
            <h2 class="my-5">{% if update %}Update Type{% else %}Create a Type{% endif %}</h2>
            <form method="POST" enctype="multipart/form-data" class="assest-cat-type">
                {% csrf_token %}
                <div class="form-group">
                    <label>Asset Type Name</label>
                    <input type="text" class="form-control my-colorpicker1 colorpicker-element {% if form.email.errors %}is-invalid{% endif %}"
                         data-colorpicker-id="1" name="asset_cat" value='{{ form.asset_cat.value|default:"" }}' id="id_asset_cat">
                </div>
            

                <div class="row">
                    <div class="col-sm-12">
                        <div class="form-group">
                        <label>Discription</label>
                            <textarea class="form-control" rows="3"  id="id_asset_discription" cols="40" rows="10"
                                name="asset_discription" value='{{ form.asset_discription.value|default:"" }}'>{% if update %}{{ form.asset_discription.value }}{% endif%}</textarea>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary ml-2" type="submit">{% if update %}Update{% else %}Save{% endif %}</button>
                {% if update %}<button type="button" id='delete-btn-type' class="btn btn-danger"><a style="color: white;" href="{% url 'asset:delete_asst_cat' obj_id %}">Delete</a></button>
                {% endif %}
             </form>
        </div>
    </div> 
{% endblock  %}

{% block js_block %} 
    <script>
        document.getElementById('delete-btn-type').addEventListener('click', function(event) {
            // Prevent the default behavior of the link
            event.preventDefault();
            
            // Display an alert message
            var confirmation = confirm("Are you sure? If you delete this asset type, all assets under this asset type will be deleted too!");
            
            // If user confirms deletion, proceed with the link action
            if (confirmation) {
                window.location.href = this.querySelector('a').href;
            }
        });
    </script>
{% endblock %}