asset/urls.py
from django.urls import path
from .views import (create_asset_cat,list_asset_cat,list_asset_manage,retrive_update_asset_manage,generate_csv,add_image_asset,
                   pie_chart,retrive_update_asset_type,delete_asst_type,create_asset_manage,delete_asst_mang_new,bar_chart_view)
app_name ="asset"

urlpatterns = [
    path('asset-catg/',create_asset_cat, name='asst_catg'),
    path('list-asset-cat/',list_asset_cat,name='lst_ast_catg'),
    path('assest-type-details/<int:pk>/', retrive_update_asset_type, name='record_details'),
    path('delete/<int:pk>/', delete_asst_type, name='delete_asst_cat'),
    path('asset-manage/',create_asset_manage, name='asst_manage'),
    path('list-asset-manage/',list_asset_manage,name='lst_ast_manage'),
    path('assest-manage-details/<int:pk>/', retrive_update_asset_manage, name='record_manage_details'),
    path('generate-csv/', generate_csv, name='generate_csv'),
    path('pie-chart/', pie_chart, name='pie_chart'),
    path('bar-chart/', bar_chart_view, name='bar-chart'),
    path('delete-new/<int:pk>/', delete_asst_mang_new, name='delete_asst_mang_new'),
    path('asset-images/',add_image_asset,name='add_images')

]

assettracker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings  
from django.conf.urls.static import static  

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/',include('authentication.urls')),
    path('home/',include('dashboard.urls')),
    path('asst/',include('asset.urls')),
]
# if settings.DEBUG:  
#         urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

authentication/urls.py
from django.urls import path
from .views import signup ,log_in,log_out

app_name ="authentication"

urlpatterns = [
    # path('signup/', signup, name='signup'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
]

dashboard/urls.py
from django.urls import path
from .views import home_page,home_page_pi

app_name = 'dashboard'
urlpatterns = [
    path('', home_page, name='home'),## Now Not used
    path('chart/', home_page_pi, name='home_pi'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render,redirect 
from django.contrib.auth.decorators import login_required

## This is Parent home page which are extended by other 
@login_required
def home_page(request):
    if request.user.is_authenticated:
        if request.user.is_superuser:
            return render(request, 'dashboard/home.html')
        # else:
        #     # Redirect regular users to a different page or perform other actions
        #     return render(request, 'regular_user_home.html')
    else:
        return render(request, 'authentication/login.html')

##This home page which return chart extended from home
@login_required
def home_page_pi(request):
    
    if request.user.is_authenticated:
        if request.user.is_superuser:
            return render(request, 'dashboard/home_pi.html')
        
    return render(request, 'authentication/login.html') 

templates/dashboard/home.html
{% extends 'base.html' %}
{% block head_title %}Home Dashboard{% endblock %}
{% block stylesheet_block %}
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
{% endblock %}

{% block blank_body %}
<div class="wrapper">
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'dashboard:home_pi' %}" class="nav-link">Home</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
    
      <li class="nav-item dropdown user-menu">
        <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <img src="../../dist/img/user2-160x160.jpg" class="user-image img-circle elevation-2" alt="User Image">
        </a>
          <ul class="dropdown-menu dropdown-menu-lg dropdown-menu-right" style="left: inherit; right: 0px;">

        <li class="user-header bg-primary">
          <p>
          Test - Web Developer
          <small>Member since Nov. 2012</small>
          </p>
        </li>
          <li class="user-footer">
            <a href="#" class="btn btn-default btn-flat">Profile</a>
            <a href="{% url 'authentication:logout' %}" class="btn btn-default btn-flat float-right">Sign out</a>
          </li>
        </ul>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <span class="brand-text font-weight-light">AssetTracker</span>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="info">
          <a href="#" class="d-block">SALMAN</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item menu-open">
            <a href="#" class="nav-link active">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
          </li>

          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-edit"></i>
              <p>
                Create Menu
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url "asset:asst_catg" %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Asset Type</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url "asset:asst_manage" %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Asset Create</p>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-table"></i>
              <p>
                DataTables
                <i class="fas fa-angle-left right"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{% url "asset:lst_ast_catg" %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Assest Type Table</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url "asset:lst_ast_manage" %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Assest Managemet Table</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{% url "asset:add_images" %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Image</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
      <div class="container-fluid">
      {% block home_main_content %} {% endblock  %}
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <strong>Copyright &copy; 2014-2021 <a href="https://www.google.co">Google</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
      <b>Version</b> 3.2.0
    </div>
  </footer>
</div>

{% endblock %}

{% block js_block%}
<script src="plugins/chart.js/Chart.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="dist/js/demo.js"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="dist/js/pages/dashboard3.js"></script>

{% endblock%}

templates/dashboard/home_pi.html
{% extends 'dashboard/home.html' %}
{% comment %} {% extends 'base2.html' %} {% endcomment %}


{% block home_main_content %} 
  <section class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Pie Chart</h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
            <div class="card-body">
              <div class="chart">
                <div class="chartjs-size-monitor">
                  <div class="chartjs-size-monitor-expand">
                    <div class=""></div>
                  </div>
                  <div class="chartjs-size-monitor-shrink">
                    <div class=""></div>
                  </div>
                </div>
                <canvas id="pie-chart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%; display: block; width: 378px;" width="378" height="250" class="chartjs-render-monitor" data-url="{% url 'asset:pie_chart' %}"></canvas>
                </div>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="card card-info">
            <div class="card-header">
              <h3 class="card-title">Bar Chart</h3>
              <div class="card-tools">
                <button type="button" class="btn btn-tool" data-card-widget="collapse">
                  <i class="fas fa-minus"></i>
                </button>
                <button type="button" class="btn btn-tool" data-card-widget="remove">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
            <div class="card-body">
              <div class="chart">
                <div class="chartjs-size-monitor">
                  <div class="chartjs-size-monitor-expand">
                    <div class=""></div>
                  </div>
                  <div class="chartjs-size-monitor-shrink">
                    <div class=""></div>
                  </div>
                </div>
                {% comment %} <canvas id="lineChart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%; display: block; width: 378px;" width="378" height="250" class="chartjs-render-monitor"></canvas> {% endcomment %}
                <canvas id="bar-chart" style="min-height: 250px; height: 250px; max-height: 250px; max-width: 100%; display: block; width: 378px;" width="378" height="250" class="chartjs-render-monitor" data-url="{% url 'asset:bar-chart' %}"></canvas>
            </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  

{% endblock  %}

{% block js_block %}
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>

    <script>

        $(function () {
    
          var $populationChart = $("#pie-chart");
          $.ajax({
            url: $populationChart.data("url"),
            success: function (data) {
    
            var ctx = $populationChart[0].getContext("2d");
            
            new Chart(ctx, {
            type: 'pie',
            data: {
                labels: data.labels,
                datasets: [{
                data: data.data,
                backgroundColor: [
                    'red',
                    'blue',
                    'green',
                    'yellow',
                    'magenta'
                ]
                }]
            },
            options: {
                responsive: true,
                title: {
                display: true,
                text: 'Pie Chart'
                }
            }
            });
    
            }
          });
    
        });
    
    </script>

    <script>
        $(function () {
          var $barChart = $("#bar-chart");
          $.ajax({
            url: $barChart.data("url"),
            success: function (data) {
              var ctx = $barChart[0].getContext("2d");
              new Chart(ctx, {
                type: 'bar',
                data: {
                  labels: data.labels,
                  datasets: [
                    {
                      label: 'Active',
                      backgroundColor: 'blue',
                      data: data.active_data
                    },
                    {
                      label: 'Inactive',
                      backgroundColor: 'red',
                      data: data.inactive_data
                    }
                  ]
                },
                options: {
                  responsive: true,
                  legend: {
                    position: 'top',
                  },
                  title: {
                    display: true,
                    text: 'Bar Chart with Active and Inactive Categories'
                  }
                }
              });
            }
          });
        });
      </script>
    
{% endblock %}